import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  author: text("author").notNull().default(""),
  language: text("language").notNull().default("pt-BR"),
  coverImage: text("cover_image"),
  isbn: text("isbn"),
  categories: text("categories"),
  keywords: text("keywords"),
  copyrightYear: text("copyright_year"),
  edition: text("edition"),
  publisher: text("publisher"),
  settingsTheme: text("settings_theme").default("classic"),
  settingsPageFormat: text("settings_format").default("6x9"),
  settingsFontFamily: text("settings_font_family").default("Georgia"),
  settingsFontSize: integer("settings_font_size").default(11),
  settingsLineHeight: text("settings_line_height").default("1.4"),
  settingsIncludePageNumbers: integer("settings_page_numbers").default(1),
  settingsIncludeToc: integer("settings_toc").default(1),
  settingsMarginTop: text("settings_margin_top").default("2cm"),
  settingsMarginBottom: text("settings_margin_bottom").default("2cm"),
  settingsMarginInner: text("settings_margin_inner").default("2.5cm"),
  settingsMarginOuter: text("settings_margin_outer").default("2cm"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const chapters = sqliteTable("chapters", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  title: text("title").notNull(),
  content: text("content"),
  order: integer("order").notNull().default(0),
  tags: text("tags"),
  type: text("type"),
  subType: text("sub_type"),
  characters: text("characters"),
  locations: text("locations"),
  partId: text("part_id"),
  number: integer("number"),
  wordCount: integer("word_count"),
  status: text("status"),
  notes: text("notes"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const characters = sqliteTable("characters", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  role: text("role"),
  tags: text("tags"),
  physicalTraits: text("physical_traits"),
  personality: text("personality"),
  motivations: text("motivations"),
  imageUrl: text("image_url"),
  relationships: text("relationships"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const locations = sqliteTable("locations", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  tags: text("tags"),
  imageUrl: text("image_url"),
  type: text("type"),
  parentLocationId: text("parent_location_id"),
  sensoryDetails: text("sensory_details"),
  cultureAndHistory: text("culture_and_history"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const timelineEvents = sqliteTable("timeline_events", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  date: text("date"),
  tags: text("tags"),
  order: integer("order").notNull().default(0),
  timeRange: text("time_range"),
  characterIds: text("character_ids"),
  locationId: text("location_id"),
  chapterId: text("chapter_id"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
