import { sqliteTable, text, integer, blob } from "drizzle-orm/sqlite-core";

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  author: text("author").notNull(),
  description: text("description"),
  coverImage: text("cover_image"),
  status: text("status"),
  targetAudience: text("target_audience"),
  wordCount: integer("word_count"),
  settingsTheme: text("settings_theme"),
  settingsLayout: text("settings_layout"),
  settingsExportFormats: text("settings_export_formats"),
  settingsPageFormat: text("settings_page_format"),
  settingsFontFamily: text("settings_font_family"),
  settingsFontSize: text("settings_font_size"),
  settingsLineHeight: text("settings_line_height"),
  settingsMarginTop: text("settings_margin_top"),
  settingsMarginBottom: text("settings_margin_bottom"),
  settingsMarginInner: text("settings_margin_inner"),
  settingsMarginOuter: text("settings_margin_outer"),
  includeToc: integer("include_toc"),
  language: text("language"),
  categories: text("categories"),
  keywords: text("keywords"),
  isbn: text("isbn"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const chapters = sqliteTable("chapters", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  type: text("type").notNull(),
  subType: text("sub_type"),
  partId: text("part_id"),
  number: integer("number"),
  title: text("title").notNull(),
  content: text("content"),
  wordCount: integer("word_count"),
  tags: text("tags"),
  status: text("status"),
  notes: text("notes"),
  order: integer("order").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const characters = sqliteTable("characters", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  role: text("role"),
  avatar: text("avatar"),
  traits: text("traits"),
  relationships: text("relationships"),
  physicalTraits: text("physical_traits"),
  psychologicalTraits: text("psychological_traits"),
  personality: text("personality"),
  motivations: text("motivations"),
  imageUrl: text("image_url"),
  arc: text("arc"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const locations = sqliteTable("locations", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  type: text("type"),
  history: text("history"),
  details: text("details"),
  imageUrl: text("image_url"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const timelineEvents = sqliteTable("timeline_events", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  date: text("date"),
  type: text("type"),
  order: integer("order").notNull(),
  characters: text("characters"),
  characterIds: text("character_ids"),
  locations: text("locations"),
  locationId: text("location_id"),
  chapterId: text("chapter_id"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
