name = "editora-web"
compatibility_date = "2025-06-26"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "editora-db"
database_id = "d4044a86-61a2-4fd1-bc16-0616ba8cb619"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "editora-assets"
